### ISSUE TITLE
Mike Urban 2019 to Mike Urban 2020 - Could not load file or assembly 'Antlr4.Runtime, Version=4.4.0.0...'

### ISSUE THREAD

**Issue by lizaclark** [DHI/Mike1D-SDK-examples#5] opened 2020-09-18 22:30 UTC
I recoded [M1DSimulatorExample1.m](https://github.com/DHI/Mike1D-SDK-examples/blob/master/mike1d-rtc-simulator-example/M1DSimulatorExample1.m) into python 3. This functioned until I installed Mike Urban 2020 and changed the SDK path `MIKE_SDK_path = 'C:\\Program Files (x86)\\DHI\\2020\\bin\\'`.  The error I see after installing Mike Urban 2020 is:

```---------------------------------------------------------------------------
FileNotFoundException                     Traceback (most recent call last)
<ipython-input-2-dcea9bdaa6b6> in <module>
      7 from_dt = System.DateTime(2014, 7, 12, 10, 45, 0)
      8 to_dt = System.DateTime(2014, 7, 12, 10, 55, 0)
----> 9 simulator.PrepareSimulation(from_dt, to_dt)
     10 print(simulator.SimulationStart.Date)

FileNotFoundException: Could not load file or assembly 'Antlr4.Runtime, Version=4.4.0.0, Culture=neutral, PublicKeyToken=bb1075973a9370c4' or one of its dependencies. The system cannot find the file specified.
   at DHI.Math.Expression.MathExpression.Compile()
   at DHI.Mike1D.ControlModule.ControlData.Initialize(Diagnostics parentDiagnostics)
   at DHI.Mike1D.Mike1DDataAccess.Mike1DController.0(Diagnostics A_0)
   at DHI.Mike1D.Mike1DDataAccess.Mike1DController.DoInitialize(IDiagnostics diagnostics)
   at DHI.Mike1D.Mike1DDataAccess.AbstractMike1DController.Initialize(IDiagnostics diagnostics)
   at DHI.M1DSimulator.M1DSimulatorRunner.PrepareSimulation(DateTime from, DateTime to)
   at DHI.M1DSimulator.M1DSimulator.PrepareSimulation(DateTime from, DateTime to)
```
I have C:\Program Files (x86)\DHI\2020\bin\DHI.Math.Expression.dll - version 18.1.0.14122. According to [NuGet](https://www.nuget.org/packages/DHI.Math.Expression/18.1.0), this dll depends on Antlr4.Runtime.Standard (>= 4.7.2). I have C:\Program Files (x86)\DHI\2020\bin\x64\Antlr4.Runtime.Standard.dll - version 4.7.2.
Have you had any issues with Antlr4.Runtime?

For reference, the code looks like this:
```python
import sys
# specify path to the DHI assemblies
MIKE_SDK_path = 'C:\\Program Files (x86)\\DHI\\2020\\bin\\'
sys.path.append(MIKE_SDK_path)
sys.path.append(r'C:\Users\eclark\Documents\GitHub\Mike1D-SDK-examples\mike1d-rtc-simulator-example\Release')
import clr
clr.AddReference('DHI.M1DSimulator')
clr.AddReference('DHI.Mike.Install')
clr.AddReference('System')
# import functions from dlls, etc
from DHI.Mike.Install import MikeImport
import System
import DHI.M1DSimulator
MikeImport.SetupLatest()

# initialize simulator with example case
modelFilePath = r'.\MU\RTCExampleBase.m1dx'
simulator = DHI.M1DSimulator.M1DSimulatorRtc(modelFilePath)

# Add water volume to result file
simulator.SetQuantitiesOfResultSpecification(System.Array[str](['WaterVolume', 'Discharge']))

# Set simulation start and end, print before and after to make sure it worked
print(simulator.SimulationStart.Date)
print(simulator.SimulationEnd.Date)
from_dt = System.DateTime(2014, 7, 12, 10, 45, 0)
to_dt = System.DateTime(2014, 7, 12, 10, 55, 0)
simulator.PrepareSimulation(from_dt, to_dt)
print(simulator.SimulationStart.Date)
print(simulator.SimulationEnd.Date)
```

**Comment by rhaDHI** [comment] 2020-09-21 13:03
Hi @lizaclark,
I hope the code example has been helpful so far 👍 
I am pretty sure the problem is related to a mismatch between the dll's that I compiled in the release folder of this repo and your the new MIKE upgrade. You need to build the DHI.M1DSimulator C# project using the new Mike1D dll's released with MIKE 2020 and replace the ones in the release folder. The new Mike1D should be available via NuGet. If you don't know how, I will try to do it when I find time. 

@JesperGr Is it simply the latest Mike1D version on nuget? 

The code was basically only meant as an C# example, but I added the dll's so users can see how to use it from e.g. matlab or python.

**Comment by JesperGr** [comment] 2020-09-22 20:31
For Release 2020 the MIKE 1D assemblies are available through NuGet, so that should do the trick.

The DHI.M1DSimulator will need to be rebuild for every release of MIKE Software. The DHI.M1DSimulator is a .NET wrapper around a .NET API, to make some things easier when working with MIKE 1D. Though, you can always use the MIKE 1D .NET API directly, in which case the script would work out of the box even when updating to the next MIKE release version. Especially, if you are not utilizing any of the more advanced parts of the DHI.M1DSimulator, I would recommend looking into using the MIKE 1D .NET API directly, instead of the going through the DHI.M1DSimulator.

@rhiDHI Maybe we should look into what could easily be added to the MIKE 1D codebase for providing something similar as what the DHI.M1DSimulator does?

**Closed** 2020-12-17 21:37 UTC
